# Dependencies
markdown:         	kramdown
pygments:         	true

# Permalinks
permalink:        	pretty

# Setup
<<<<<<< HEAD
title:            RMUoHP Physician Assistant Program
tagline:          'Educating Clinicians to Practice in a Digital World'
description:      'educating <span style="color:#f8c790">self-reflective professionals</span> who value and practice <span style="color:#f8f89c">evidence-based</span>, <span style="color:#91e691">patient-centered care</span> in a <span style="color:#f89d9d">digitally pervasive world</span>'
url:              http://rmupap.github.io
=======
title:            	RMUoHP Physician Assistant Program
tagline:          	'Educating Clinicians to Practice in a Digital World'
description:      	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:85%;">educating</span><br/><span style="color:#f8c19d">&nbsp;&nbsp;&nbsp;reflective professionals</span><br/>&nbsp;<span style="font-size:85%;">who value and practice</span><br/><span style="color:#f8f89c">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;evidence-based,</span><br/><span style="color:#9eebaa">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;patient-centered care</span><br/><span style="font-size:85%;">&nbsp;&nbsp;in the context of a</span><br/><span style="color:#f89d9d">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;digitally demanding world</span>'
url:              	http://rmupap.github.io
>>>>>>> FETCH_HEAD

author:
  name:           	'David Payne'
  url:            	https://twitter.com/DavidAPaynePAC

# Custom vars
version:          	2.0.0
github:				davidpaynepac
caspa:				https://portal.caspaonline.org
dP:					http://bit.ly/dP-CV
