# Dependencies
markdown:         	kramdown
pygments:         	true

# Permalinks
permalink:        	pretty

# Setup
title:            	Rocky Mountain University of Health Professions Physician Assistant Program
tagline:          	'Educating Clinicians to Practice in a Digital World'
description:		'<span style="font-size:85%;">educating</span><span style="color:#f8c790"> reflective professionals</span><span style="font-size:85%;"> who value and practice</span><span style="color:#f8f89c"> evidence-based,</span><span style="color:#9eebaa"> patient-centered care</span><span style="font-size:85%;"> in the context of a</span><span style="color:#f89d9d"> digitally demanding world</span>'
url:              	http://rmupap.github.io

author:
  name:           	'David Payne'
  url:            	https://twitter.com/DavidAPaynePAC

paginate:			5
paginate_path: 		"blog/page:num"
safe:				false

# Custom vars
version:          	2.0.0
github:				davidpaynepac
caspa:				https://portal.caspaonline.org
dP:					http://bit.ly/dP-CV
imagepath:			https://googledrive.com/host/0B8sxZSEkeQweQjQxa1l1dlNTaWc
hubroot: 			https://hub.rockypa.com/