# Dependencies
markdown:         	kramdown
highlighter:        pygments

# Permalinks
permalink:        	pretty

# Setup
title:            	Rocky Mountain University of Health Professions Physician Assistant Program
tagline:          	'Educating Clinicians to Practice in a Digital World'
description:		'educating reflective professionals who value and practice evidence-based, patient-centered care in the context of a digitally demanding world'
url:              	http://rmupap.github.io

author:
  name:           	'David Payne'
  url:            	https://twitter.com/DavidAPaynePAC

paginate:			5
paginate_path: 		"blog/page:num"
safe:				false

# Custom vars
version:          	2.0.0
github:				davidpaynepac
caspa:				https://portal.caspaonline.org
dP:					http://bit.ly/dP-CV
imagepath:			https://googledrive.com/host/0B8sxZSEkeQweQjQxa1l1dlNTaWc
hubroot: 			https://pahub.rmuohp.edu/